import os
import sys

# --- Terminal UI Colors ---
class Colors:
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def install_hook():
    print(f"\n{Colors.OKCYAN}{Colors.BOLD}========================================={Colors.ENDC}")
    print(f"{Colors.OKCYAN}{Colors.BOLD}🛡️  SECRET SCANNER INSTALLER 🛡️{Colors.ENDC}")
    print(f"{Colors.OKCYAN}{Colors.BOLD}========================================={Colors.ENDC}\n")

    # Get paths
    current_dir = os.path.abspath(os.getcwd())
    git_dir = os.path.join(current_dir, '.git')
    hooks_dir = os.path.join(git_dir, 'hooks')
    pre_commit_file = os.path.join(hooks_dir, 'pre-commit')
    scanner_script = os.path.join(current_dir, 'secret_scanner.py')

    if not os.path.exists(git_dir):
        print(f"{Colors.FAIL}✖ Error: Not a Git repository!{Colors.ENDC}")
        print(f"Please run this script from the root of a Git repository.")
        sys.exit(1)

    if not os.path.exists(scanner_script):
        print(f"{Colors.FAIL}✖ Error: 'secret_scanner.py' not found in current directory!{Colors.ENDC}")
        sys.exit(1)

    # Ensure hooks directory exists
    os.makedirs(hooks_dir, exist_ok=True)

    # The bash script that will run the python scanner
    hook_content = f"""#!/bin/bash
# ----------------------------------------------------
# Secret Scanner Pre-commit Hook
# Auto-generated by install.py
# ----------------------------------------------------

echo "Running Secret Scanner..."
python "{scanner_script}"
EXIT_CODE=$?

# If python script returns non-zero, block the commit
if [ $EXIT_CODE -ne 0 ]; then
    exit 1
fi
exit 0
"""

    try:
        with open(pre_commit_file, 'w', encoding='utf-8') as f:
            f.write(hook_content)
            
        # Make the hook executable on Unix-based systems (Git Bash on Windows respects this)
        try:
            os.chmod(pre_commit_file, 0o755)
        except Exception:
            pass # Windows permission handling varies, but Git for Windows handles it natively usually.

        print(f"{Colors.OKGREEN}✅ Successfully installed pre-commit hook!{Colors.ENDC}")
        print(f"The hook is located at: {pre_commit_file}")
        print(f"Every time you run 'git commit', your code will be scanned for secrets.\n")
        
    except Exception as e:
        print(f"{Colors.FAIL}✖ Error writing hook file: {e}{Colors.ENDC}")
        sys.exit(1)

if __name__ == "__main__":
    install_hook()
